FROM node:14-alpine AS builder

WORKDIR /usr/app

COPY package.json .
RUN yarn install
COPY . .

RUN yarn build

FROM nginx:1.19.0-alpine

WORKDIR /usr/app
COPY --from=builder /usr/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]